# $Id: Makefile 147 2004-12-18 09:18:39Z song $

all:
#@mysqldump -uZebra --no-data --quote-names -v SuperServer > SuperServer.sql
	@mysqldump -uZebra --no-data --quote-names -v LoginServer > LoginServer.sql
	@mysqldump -uZebra --no-data --quote-names -v RecordServer > RecordServer.sql

